/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diana_alfred_bscs111_12062024;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class AdminGUI extends javax.swing.JFrame {
    public static Hashmaps hm = new Hashmaps();
    public static int orderID;
    public AdminGUI() {
        initComponents();
        dispUserTable();
        dispFoodTable();
    }
    
    public static void dispUserTable(){
        
        DefaultTableModel tblm = new DefaultTableModel();
        tblm.setColumnIdentifiers(new String[]{"ID", "Full Name", "Password", "Contact No", "Address", "Gender", "Type"});
        
        for(int PID : hm.acctList.keySet()){
            
            String[] PDat = hm.acctList.get(PID);
            tblm.addRow(new Object[]{PID, PDat[0], PDat[1], PDat[2], PDat[3], PDat[4], PDat[5] });
        }
        
        userAccTable.setModel(tblm);
        userAccTable.setDefaultEditor(Object.class, null);
    }
    
    public static void dispFoodTable(){
        DefaultTableModel tblm = new DefaultTableModel();
        tblm.setColumnIdentifiers(new String[]{"ID", "Food name", "Price", "Quantity"});
        
        for(int PID : hm.prodList.keySet()){
            
            String[] PDat = hm.prodList.get(PID);
            tblm.addRow(new Object[]{PID, PDat[0], PDat[1], PDat[2]});
        }
        
        foodListTable.setModel(tblm);
        foodListTable.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userAccTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        foodListTable = new javax.swing.JTable();
        editUserBtn = new javax.swing.JButton();
        editFoodBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        DelUsrBtn = new javax.swing.JButton();
        AddFoodBtn = new javax.swing.JButton();
        DelFoodBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Admin Menu");

        jScrollPane1.setViewportView(userAccTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("User Accounts");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Food List");

        jScrollPane2.setViewportView(foodListTable);

        editUserBtn.setText("Edit User");
        editUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserBtnActionPerformed(evt);
            }
        });

        editFoodBtn.setText("Edit Product");
        editFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFoodBtnActionPerformed(evt);
            }
        });

        logOutBtn.setText("Log Out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        DelUsrBtn.setText("Delete User");
        DelUsrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelUsrBtnActionPerformed(evt);
            }
        });

        AddFoodBtn.setText("Add Product");
        AddFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFoodBtnActionPerformed(evt);
            }
        });

        DelFoodBtn.setText("Delete Product");
        DelFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelFoodBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 403, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(319, 319, 319)
                                .addComponent(logOutBtn)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(422, 422, 422))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addGap(437, 437, 437))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(editUserBtn)
                        .addGap(42, 42, 42)
                        .addComponent(DelUsrBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(AddFoodBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editFoodBtn)
                        .addGap(18, 18, 18)
                        .addComponent(DelFoodBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(logOutBtn))
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editUserBtn)
                    .addComponent(DelUsrBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editFoodBtn)
                    .addComponent(AddFoodBtn)
                    .addComponent(DelFoodBtn))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserBtnActionPerformed
       
        if(userAccTable.getSelectedRow()== -1){
            JOptionPane.showMessageDialog(this, "Select a user!");
        }else{
        int column = 0;
        int row = userAccTable.getSelectedRow();
        orderID = (int) userAccTable.getValueAt(row, column);
        UserEdit ue = new UserEdit();
        ue.show();
        this.dispose();
        }
        
    }//GEN-LAST:event_editUserBtnActionPerformed

    private void editFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFoodBtnActionPerformed
        
        if(foodListTable.getSelectedRow()== -1){
            JOptionPane.showMessageDialog(this, "Select a product!");
        }else{
        int column = 0;
        int row = foodListTable.getSelectedRow();
        orderID = (int) foodListTable.getValueAt(row, column);
        FoodEdit fe = new FoodEdit();
        fe.show();
        this.dispose();
        }
        
    }//GEN-LAST:event_editFoodBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        Login lg = new Login();
       lg.show();
       this.dispose();
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void AddFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFoodBtnActionPerformed
        AddFood af = new AddFood();
        af.show();
        this.dispose();
    }//GEN-LAST:event_AddFoodBtnActionPerformed

    private void DelFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelFoodBtnActionPerformed
        if(foodListTable.getSelectedRow()== -1){
            JOptionPane.showMessageDialog(this, "Select a product!");
        } else{
        int choice = JOptionPane.showConfirmDialog(this,  "Are you sure?","",JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION){
            int column = 0;
        int row = foodListTable.getSelectedRow();
        orderID = (int) foodListTable.getValueAt(row, column);
            
            hm.prodList.remove(orderID);
            dispFoodTable();
        }else{
            
        }
       }
    }//GEN-LAST:event_DelFoodBtnActionPerformed

    private void DelUsrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelUsrBtnActionPerformed
       if(userAccTable.getSelectedRow()== -1){
            JOptionPane.showMessageDialog(this, "Select a user!");
        } else{
        int choice = JOptionPane.showConfirmDialog(this,  "Are you sure?","",JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION){
            int column = 0;
        int row = userAccTable.getSelectedRow();
        orderID = (int) userAccTable.getValueAt(row, column);
            
            hm.acctList.remove(orderID);
            dispUserTable();
        }else{
            
        }
       }
    }//GEN-LAST:event_DelUsrBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFoodBtn;
    private javax.swing.JButton DelFoodBtn;
    private javax.swing.JButton DelUsrBtn;
    private javax.swing.JButton editFoodBtn;
    private javax.swing.JButton editUserBtn;
    public static javax.swing.JTable foodListTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOutBtn;
    public static javax.swing.JTable userAccTable;
    // End of variables declaration//GEN-END:variables
}
